# Generated by Django 5.1.3 on 2025-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите заголовок поста",
                        max_length=100,
                        verbose_name="Заголовок поста",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите текст поста",
                        null=True,
                        verbose_name="Основной текст",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте изображение для поста",
                        null=True,
                        upload_to="post/image",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Added",
                        null=True,
                        verbose_name="Date Added",
                    ),
                ),
                (
                    "was_publication",
                    models.BooleanField(
                        default=True,
                        help_text="Статус публикации поста",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["description", "name"],
            },
        ),
    ]
